# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'swift网络请求第三方库' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for swift网络请求第三方库

pod 'Alamofire'
pod 'Kingfisher'
pod 'SwiftyJSON'
end
